### ISSUE TITLE
Discussion: how should we handle cycles in data?

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/interpretation#10]
In the process of building a nested version of the examples, I ran into a problem with the fact that `CanonicalAllele`s refer to a `preferredCtxAllele` and `ContextualAllele`s refer back to a `CanonicalAllele`, creating a cycle that is not straightforward to represent in standard JSON.

Possible ways to proceed:

1. Special-case one or the other of `CanonicalAllele` or `ContextualAllele` to break the cycle by just referring to the other by id. This is what I have done in commit e1de1e5, but I don't think it is necessarily the best solution.
2. Customize presentation of structures such that sub-records can be referred to by id or placed in-line.
3. Allow representation of cycles within the data structures (YAML allows this natively, I think that this could be done in JSON or XML with JSON references or XPATH internal references respectively, but I don't think the ruby standard JSON serializer supports this).

**Comment by cbizon** [comment]
I don't believe that preferredCtxAllele is an actual attribute in the allele model.   

The simplest thing to do, if I am right, is simply remove that attribute.
