### ISSUE TITLE
Activity.when

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/interpretation#12]
In Prov, there is not a "when" but a "startedAtTime" and "endedAtTime" which time-bounds the activity.

Do we want to stick to prov here?

It would be straightforward to change when to startedAtTime, but then we would need to add endedAtTime to all the examples.

**Comment by rrfreimuth** [comment]
Does Prov [started/ended]AtTime have any restriction on the level of granularity?  e.g., full timestamp with fractions of a second vs. hour vs. day vs. week vs. year...

**Comment by larrybabb** [comment]
I presume that the W3C model can be implemented such that you can define the granularity of time according to specific use cases.  I don't think there's any restrictions or constraints.

**Comment by cbizon** [comment]
Larry to replace when with startedAtTime/endedAtTime in the spreadsheet

**Comment by larrybabb** [comment]
done
