### ISSUE TITLE
Fix inconsistent agent use in activities

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/interpretation#13]
Activity has (as in prov) a wasAssociatedWith Agent attribute.

To specialize, we have added attributes to each activity with names like 'assessor', 'curator' etc, that encode the same information.  This is confusing.

Do we want to
1) Stick with prov, dropping 'assessor' etc
2) Stick with 'assessor', getting away from being prov-compliant
3) Some amalgam?

**Comment by bpow** [comment]
To what extent is the role implicit in the activity? If implicit, I think we should stick with prov.

**Comment by cbizon** [comment]
It is completely implicit in that each activity has a single role and each role only a single activity.

**Comment by rrfreimuth** [comment]
Is the role of the Agent captured?  (Sorry - I don't have the model open in front of me right now)

> each role only a single activity

I must be misunderstanding this.  It must be possible to express that a curator (Agent) can perform multiple activities.  Please clarify my confusion.

**Comment by cbizon** [comment]
So in prov, there is Agent.  Instances of agent can perform multiple activities.

We have subclassed Agent to a set of roles: Curator, Assessor, etc.  Each of these subclasses has a one-to-one relationship to a particular subclass of activity.

So the same e.g. Curator could be associated with multiple Curation Activities, but not with an AssessCriteria activity.  

This is actually a problem, because the same actual person could do the same work, and it's not clear to me how one person can be an instance of both types.

So I'm leaning heavily towards dropping the Agent subclasses.

**Comment by rrfreimuth** [comment]
> the same actual person could do the same work, and it's not clear to me how one person can be an instance of both types.

This didn't occur to me before you just said it.  It seems awkward to remove the additional specificity provided by the subclasses to satisfy an ontological constraint, though.  Then we're no longer modeling the domain and instead modeling the subset of the domain that can be represented precisely in a given language.  (There needs to be a balance, of course.)

> So I'm leaning heavily towards dropping the Agent subclasses.

Would we capture the information in a different way, then?  If we can't subclass Agent, could we subclass wasAssociatedWith and/or wasAttributedTo?  e.g., AssessCriterion[Activity] wasAssociatedWithAssessor Agent

Let me know if this is nonsensical.

**Comment by bpow** [comment]
I think what @cbizon is trying to get across is that the role of the `Agent` is implicit in the type of activity they are being associated with.

For instance, when someone is associated with an `AssessCriteria` activity, she is an "assessor". The same person, when performing a `CaptureData` activity, is acting as a "capturer".

If we subtype `Agent` to reflect these different roles, what would we gain? Are there additional bits of information that we would need to record for assessors vs. capturers vs. people in other roles? We currently are not doing so. Are there any activities that would have agents of different roles associated with them (if so, aren't there really two different activities going on?)?

**Comment by cbizon** [comment]
Yes, exactly what @bpow says.  It adds complexity, but without the payoff of new information.

**Comment by rrfreimuth** [comment]
> Are there additional bits of information that we would need to record for assessors vs. capturers vs. people in other roles?

That's certainly a fair question.  We only need to model it if there is a reason to.

The answer may be "yes" (there are bits of info that we want to record) - the question then becomes whether the info we capture about Agents in different roles is actually different.  If the info is the same across roles, then we probably don't need the subclasses.

**Comment by larrybabb** [comment]
I am dropping the roles in favor of the simplistic "inferred" role based on the activity. We do not need to support any higher level of complexity at this point in time.
