### ISSUE TITLE
GroupAlleleFrequency

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/interpretation#15]
We have a set of types that descend from w3c-prov entity.   Some of these are Data and its subclasses.  One of these subclasses is PopulationAlleleFrequency, which is used directly in certain CriterionAssessments.

Another type of Data is CaseControl data, which is also used directly in CriterionAssessments.  

Some of our Data elements use 'helper' types, which are not directly used in Assessments, but are used by Data.  One example is ContextualRegion.   Because it's not used directly by an assessment, we do not have ContextualRegion descend from Entity.

Now, we have 2 frequency types, GroupAlleleFrequency and PopulationAlleleFrequency.  PopulationAlleleFrequency derives from GroupAlleleFrequency and adds some attributes.  PopulationAlleleFrequency, as noted above also needs to descend from Entity.

however, GroupAlleleFrequency is a helper class, it's only used by the Entity CaseControl.  So if we follow the pattern then it would not be an Entity.  I assume that we only have single inheritance, so what do we want to do:

1) Make GroupAlleleFrequency an Entity.  It will then show up under "Data" and have wasGeneratedBy even though we don't ever use it in that way.

Actually, I think that this is the only real solution, it's just sort of messy, and I wanted to run it by everybody to see what they thought.

**Comment by rrfreimuth** [comment]
Why is PopulationAlleleFrequency necessary as a separate class?  Why not move the two attributes in that class to GroupAlleleFrequency and then make GAF an Entity rather than a helper class?

**Comment by larrybabb** [comment]
closed. We combined the two concepts into AlleleFrequency. see #21 for more details.
