### ISSUE TITLE
What is the relationship of Criterion to AssertionMethod?

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/interpretation#19]
A recent change to the sheet (I presume by @lbabb) created an `assertionMethod` attribute of criterion, with type `AssertionMethod`.

For one thing, this creates a loop (ala #10), which would have to be special-case excluded from the JSON output.

For another thing, I'm not sure that the criterion-assertion relationship is one-to-one. For instance, I could envision (maybe the rasopathy group already does something like this?) two `AssertionMethod`s that are closely aligned with each other-- maybe one is derived from the other but with a different set of rules for combining the criteria, or perhaps just swapping out a few of the criteria. If both of these `AssertionMethod`s still have the same 'BA1', shouldn't they be represented by the same 'BA1'? That makes the similarities/differences between the two methods much clearer.

For now, I'm going to back-out the attribute on Criterion to break the loop, but this is of course open for further discussion.

**Comment by rrfreimuth** [comment]
Very interesting point on the cardinality between criterion and assertion.  I like your example – it mirrors some of the things we’re doing at Mayo in our enterprise knowledge management group – but cannot say how likely that scenario is.  Hoping others can comment on that aspect.

Thanks,
Bob

**Comment by larrybabb** [comment]
I agree. I will change it to a many-to-many so that a given evidence rule (aka Criterion) can be used in more than one assertion method (or more than one version of the same assertion method).
