### ISSUE TITLE
Guideline vs CriteriaSet

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/interpretation#2]
In the VariantInterpretation class in VisualParadigm, we have an attribute called criteriaSet

In the spreadsheet, this is called Guideline.

I changed the spreadsheet to match the VP.

Which do we want?

**Comment by bpow** [comment]
I like criteriaSet, myself.

Note that this affects:
* The name of the entity E32 (Guideline) and E33 (GuidelineAlgorithm)
* The name of the sheet 'Guideline'
* The name of attribute A124
* The name of attribute A152
* The header 'criteriaSet' in 'VariantInterpretation'
* The header 'guideline' in 'Criterion'

Maybe other places?

**Comment by larrybabb** [comment]
I changed CriteriaSet to Guideline (and forgot to mention it – oops).  I understand that it is not perfect, but I wanted to find a term that was a bit less technical and aligned more with the user community.  I’ve heard methodology, process, guideline, and assertion method (clinvar).  Maybe “assertion method” is best or just “method” so that we move closer to the “assertion” concept used by SEPIO.

**Comment by bpow** [comment]
I'm open to discussion on the name of this. I would discourage "Process" since this word has the noun-verb duality problem.

For now, I'm about to work on #6, and need to have some more consistency/referential integrity in the sheets document, so I am going to try to make the minimal changes necessary to work on that.

**Comment by tnavatar** [comment]
Guideline seems to fit our domain well, I’m trying to think if there’s anything it wouldn’t cover when we get beyond the ACMG criteria. I can’t think of anything right now.

**Comment by cbizon** [comment]
On call 11/9, we decided on Method

**Comment by bpow** [comment]
Should we have `Guideline` different from `GuidelineAlgorithm`? If so, what is the distinction in what they represent? I lean towards merging both into `Method`. Comments (especially from @larrybabb)?

**Comment by larrybabb** [comment]
I think we may want to differentiate between the "logic" or "calculation" and the overall umbrella for the assertion method.  But I might be swayed.  Let's drop the Algorithm concept if others agree. we can always jam it back in. I don't think it too core to our various models and associated concepts.

**Comment by cbizon** [comment]
I like having the combining algorithm having a separate existence.     I guess it comes down to : if somebody used AMCG guidelines, but instead of following the recs on how to combine assessed criteria they modified the combination criteria to make it harder to call something pathogenic (for instance).  Would we want to call that a whole new Method, or same Method, different combining algorithm?

**Comment by rrfreimuth** [comment]
I agree - I'd prefer to keep the concept of a guideline separate from the individual criteria from the aggregating algorithm.  This will also allow us to more easily extend the model (if needed) to capture other information about a guideline.

**Comment by bpow** [comment]
In that case, I think we should re-discuss how to name the two different things. The way things are written in the ACMG manuscript are that the "standards and guidelines" (overall title of the paper) consist of a set of "criteria" (tables 3 and 4) as well as "rules" for combining these criteria (table 5). I'm not saying that we should follow this nomenclature exactly, but that it serves as one mapping of these concepts to terms.

If we divide this into two separate concepts, there are the set of criteria and the methodology for combining/weighting these criteria.

We already differentiate between criteria (in the `Criterion` type) and the new concept of `Method` for combining them. Do we need a separate entity to represent sets of criteria? Or do we say that a `Method` (in this case the ACMGv2015 standards/guidlelines described in the manuscript) provides a method for combining criteria. A different method could weight things differently, include additional criteria, exclude some criteria, etc...

I guess what I am saying is, what is the use case for having a separate entity to represent a set of criteria?

**Comment by cbizon** [comment]
I would say that we have a Method, or an InterpretationMethod that is an aggregate of some number of Criteria, plus a single CombinationMethod.  The list of individual rules, plus how you combine those rules defines the overall method that you used to generate the interpretation.   Aggregating them this way gives us a way to say things like, this method is just like that method, except with a different combiner or with the addition/subtraction of some of the rules (criteria).

So I would say Method is the top level thing, it has Criteria, and a Combiner(? I think that sounds dumb, what is a better name for this?)

**Comment by rrfreimuth** [comment]
Aggregator or ScoringAlgorithm?

**Comment by cbizon** [comment]
I like ScoringAlgorithm

**Comment by larrybabb** [comment]
+1 scoringAlgorithm

**Comment by cbizon** [comment]
So a Method has a ScoringAlgorithm and a list of Criteria.

Is Method specific enough?

**Comment by rrfreimuth** [comment]
I'd vote for InterpretationMethod.  Method is pretty generic and may tie our hands later.

**Comment by larrybabb** [comment]
Assertion Method is more specific and inline with SEPIO

**Comment by bpow** [comment]
How specific we need to make this term (and others...) depends on how deeply we think we might want to namespace things. We could consider one of `clingen:AssertionMethod` vs. a `clingen-interpretation:Method` as the "full" term, which might be abbreviated depending on context.

**Comment by cbizon** [comment]
AssertionMethod contains ScoringAlgorithm and a list of Criterion(s)

**Comment by cbizon** [comment]
Larry will change the sheet

**Comment by larrybabb** [comment]
completed.  Added ScoringAlgorithm "type" and associated sheet.  Modified all "method" attributes and types to "AssertionMethod". changed pk/fks to be more like other generated ids in the data to connect entities.
