### ISSUE TITLE
CaseControl attributes - clarification needed.

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/interpretation#22]
In CaseControl we have the following 4 fields that seem to be interrelated.
oddsRatio, confidenceLevel, confidenceIntervalUpper, confidenceIntervalLower.

1. Is there a difference between the first and the second?  The second being a percentage form?

2. Are the lower and upper confidenceInterval attrbutes the numerator and denominator for the oddsRatio? And, the confidenceLevel (percentage)?
If so, why both? Maybe for MVP we should just put the derived percentage or ratio?

**Comment by cbizon** [comment]
A confidence interval is a way of putting precision on a value.  So you calculate the oddsRatio and you want to put a +/- on there.   A confidence interval is that range.  Basically, you might have a calculated odds ratio of 1.5, and the other values say that you are 95% sure that the real odds ratio is between 1.4 and 1.65.  95% is the confidenceLevel, 1.4 is the Lower and 1.65 the upper.

**Comment by larrybabb** [comment]
got it.
