### ISSUE TITLE
RegionAnnotation attribute clarification.

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/interpretation#24]
The type and value attributes of RegionAnnotation need a description.

The value is listed as a boolean. So, if the value of a regionAnnotation.value is true does that mean that the region contains the target allele (not listed as an attribute)?  
When would it be used with a "false" value?

(Also need a description on the RegionAnnotation data type itself)

The "type" seems to indicate the kind of Region being expressed.  We have provided 3 potential values? Is there an ontology, standard or place we can request a full list of values for this?

**Comment by cbizon** [comment]
The value is whether or not the region is whatever is in type.  So you can say "This region is a repeat region" or "This region is not a repeat region".  (value = True, value = False).

Potentially, we can allow all sorts of annotations on a region.  The three that we came up with were specifically to be able to make statements needed for particular ACMG guidelines.

Repeat does have a term in SO - SO:0000657 repeat_region
But there's not a term for the other two.

**Comment by larrybabb** [comment]
Understood. We will provide suggested coded values but allow for others to be extended included custom ones.  see #38 in regards to CodeableConcept datatype usage.
