### ISSUE TITLE
AggSegData LODScoreType needs values

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/interpretation#27]
We need to finalize the LODScoreType value list on AggSegData.

**Comment by cbizon** [comment]
I think I might be more in favor of getting rid of it, and also dropping LOD.  I think we will rarely get such information, and it can go in the explanation if needed.

**Comment by larrybabb** [comment]
removed the two LOD score related attributes from AggSegData type.  No examples existed.  We can re-add if there's a compelling reason to do so, later.
