### ISSUE TITLE
AggSegData association to FamSegData

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/interpretation#28]
In the spirit of MVP (min viable product) how critical is the FamSegData array on the AggSegData data type?  Would the AggSegData still be reasonably useful.

(Goal: Can we achieve value in single tier data types for our first phase and still achieve a MVP that is reasonably useful?)

**Comment by cbizon** [comment]
I don't think that getting rid of the family level seg here helps us very much in terms of simplicity/complexity.  At least not as much as the hit we take in expressing the data.

**Comment by larrybabb** [comment]
ok. no changes made.
