### ISSUE TITLE
Merge IndividualAllele & IndividualCondition?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/interpretation#34]
I went thru all the data types and mapped them to the rules based on the example cases we have.  I found some patterns that may help simplify some things (or I could be spinning my wheels)…
 
For example,
 
Some of the data types seem to depend on others and thus raises the question of wheter we should consolidate them or not?
 
Ex 2: Can IndividualAllele be added to IndivdualCondition?
                IndividualAllele seems to always be paired with IndividualCondition (PM3, BS2, BP2, BP5). IndividualCondition also exists in PS2 and PM6, without IndividualAllele.

**Comment by larrybabb** [comment]
@bpow & @cbizon : Can you guys simply weigh in on whether this is reasonable or not?  I do not think the group needs to go thru each of these?  If not please leave open and we will discuss.

**Comment by bpow** [comment]
I think they should be separate for the same reasons I think FamilyHistory and DeNovoAllele are distinct: they come from different sources (again, allele comes from sequencing information, the condition is described by a clinician).

They are used together in PM3, BS2, BP2 and BP5 as you mention, but neither depends on the other from a data modeling standpoint (in fact, the whole reason of performing variant analysis is to try to assess whether or not there is a causal relationship between a particular IndividualAllele and a particular IndividualCondition, although we may use other IndividualAlleles and IndividualCondtions as part of the supporting evidence...)

**Comment by cbizon** [comment]
I'd be OK merging here, but I don't really love it, and given @bpow comment above, I think don't merge.  Closing.
