### ISSUE TITLE
Merge Condition Penetrance & Inheritance?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/interpretation#36]
I went thru all the data types and mapped them to the rules based on the example cases we have.  I found some patterns that may help simplify some things (or I could be spinning my wheels)…
 
For example,
 
Some of the data types seem to depend on others and thus raises the question of wheter we should consolidate them or not?
 
Ex 4: Can ConditionPenetrance be added to ConditionInheritance?
                ConditionPenetrance is used in rules: BS1, BS2, BP2. For each of these ConditionInheritance seems to be critical. Can we merge the Penetrance fields and make them optional?

**Comment by larrybabb** [comment]
@bpow & @cbizon : Can you guys simply weigh in on whether this is reasonable or not?  I do not think the group needs to go thru each of these?  If not please leave open and we will discuss.

**Comment by bpow** [comment]
somewhat overlapping with #37 (but merging these two makes more sense than merging prevalence with either)

**Comment by cbizon** [comment]
I don't think this one makes sense.  Closing.
