### ISSUE TITLE
Merge Condition Prevelance & Inheritance?

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/interpretation#37]
I went thru all the data types and mapped them to the rules based on the example cases we have.  I found some patterns that may help simplify some things (or I could be spinning my wheels)…
 
For example,
 
Some of the data types seem to depend on others and thus raises the question of wheter we should consolidate them or not?

Ex 5: Can ConditionPrevelance be added to/merged with ConditionInheritance? (and/or ConditionPenetrance?)
                Same as previous question, but I only found one place where Prevelance is used (BS1), and it seem to also require both Prevelance and Inheritance.

**Comment by larrybabb** [comment]
@bpow & @cbizon : Can you guys simply weigh in on whether this is reasonable or not?  I do not think the group needs to go thru each of these?  If not please leave open and we will discuss.

**Comment by bpow** [comment]
Inheritance and penetrance fit together than either with prevalance (with penetrance being possibly considered a modifier of the mode of inheritance).

My feeling is that we again fall into the issue that the different data (penetrance vs. prevalance) may come from different sources, so we may want to tag different pubmed ids, for instance. Some reviews may include both types of info, but they are often from different primary sources.

**Comment by cbizon** [comment]
I would also not merge this one.
