### ISSUE TITLE
AlleleFrequency / CanonicalAllele

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/interpretation#43]
We currently have AlleleFrequency data associated with a ContextualAllele.  It makes some sense, but I thin we should switch to a CanonicalAllele.

**Comment by rrfreimuth** [comment]
I agree.  I am having a hard time coming up with a use case that would argue for putting it on the ContextualAllele, other than simply wanting to maintain provenance regarding the source of the information (which we should still be able to do if it were on CanonicalAllele).

**Comment by larrybabb** [comment]
I agree, I'll switch to canonicalAllele
