### ISSUE TITLE
 MendelianVariantPathogenicityInterpretation

### ISSUE THREAD

**Issue by cbizon** [clingen-data-model/interpretation#45]
I think that we all agree that we want to replace this data element with a regular Interpretation.  How do we this while retaining the Data type.   Do we need to retain this type?  How does it work in SEPIO?

**Comment by bpow** [comment]
I think that what we currently call `Data` (E01) matches fairly well with the SEPIO concept of `Evidence`. I think it is reasonable to also make `CriterionAssessment`s and `VariantInterpretation`s be subtypes of `Evidence` (or `Data` if we keep that name).

The class hierarchy is a bit difficult to comprehend using the sheets document, but I think this would cause minimal difficulty.

This is consistent with my thinking that every piece of data is, to some extent, an assertion (which may or may not describe the strength of that assertion, e.g., confidence intervals, QC procedures for the measuring device). Likewise, every assertion could be used as data in some downstream analysis.

I know I've stated this on calls before, just putting it in writing to focus discussion.

**Comment by bpow** [comment]
This is, of course, the same discussion as #20

**Comment by cbizon** [comment]
oops.  Closing, as it's a dup of #20
