### ISSUE TITLE
Address inconsistencies within the sheets document

### ISSUE THREAD

**Issue by bpow** [clingen-data-model/interpretation#7]
As the sheets document has grown organically, it has developed a few inconsistencies and lacks referential integrity at a few points. This is an umbrella issue for discussion related to refactoring of this document to reduce the number of special cases in parsing.

1. make sure attribute names in individual entity sheet match attributes in the Attribute sheet
2. consider renaming the `Entity` sheet (to EntityTypes or EntityMeta)
3. consider addressing inconsistency that entities that inherit directly from `Entity` have individual sheets *except `Data`*, and that subtypes of `Data` have a different table structure (in `DataAttributes` sheet) that is organized by entity-key-value
4. come up with a consistent naming scheme for "joining" tables

**Comment by cbizon** [comment]
Can we switch from "Entity" for non-W3C entities to "Class"?

**Comment by tnavatar** [comment]
Class has special meaning in RDF (if we’re thinking ahead to integrating with SEPIO)

**Comment by bpow** [comment]
Just to clarify my suggestion to change the name of the `Entity` sheet:

In processing the sheets data, I run through the data in the `Entity` sheet, for each `name` listed therein, I look to see if we have a sheet by that name, and if so use it to populate the relevant instances of that entity type.

However, the `Entity` sheet does not currently describe instances of type *Entity*, but it rather describes the types of *Entity* and its subtypes (or subclasses).

I don't know if that makes things clearer. I'm not at all suggesting that we get rid of *Entity* as a type, but just that we rename the sheet since the data it contains are not instances.

**Comment by larrybabb** [comment]
EntityMeta or EntityTypes works for me.

**Comment by cbizon** [comment]
I'm not sure that what I am saying is responsive to this question, but I have a concern that the Entity spreadsheet contains things that are not W3C-Prov entities.  They instead are Activities and Agents.  These are separate concepts.    We use the term Entity on a row of the spreadsheet to mean W3C prov entities, but the Entity name on the spreadsheet means something broader, like "class" or "object" or something.

**Comment by cbizon** [comment]
What remains to address in this issue?

**Comment by bpow** [comment]
(1) & (2) from the original list are done.

(3) is a bit thorny because unifying to make everything like the DataAttribute table (with EAV structure) would make future editing much more difficult, while making individual tables for subclasses of Data would make for a very large number of sheets. So maybe we just leave things the way they are...

For (4), I propose that all joining tables have "Join" or "Association" as a prefix or suffix (obviously not all of those possible combinations...) These are essentially those tables that represent values with cardinality 0..* or 1..*

So, we could do something like:

| From  | To |
|---------|-----|
| ActivityAgentAssociation | JoinActivityAgent |
| ActivityUsedEntity | JoinActivityEntity |
| ContextualAlleleRelations | JoinContextualAlleles |
| ReferenceSequenceRelations | JoinReferenceSequences |
| DataAttribute | JoinDataAttribute |

That last one... note that DataAttribute doesn't really need its primary key (the PK isn't used elsewhere), so its usage fits this pattern.

The main reasons to change these names would be so that it would be easier to quickly see which tables are used in this manner, and also to use this convention to clean-up some code in `get_examples.rb` and `reformat_examples.rb`. For the latter part, we can leave the list of join tables as explicit, but I think it would be nice to have their names be more consistent. I don't think of them as user-facing tables, so it's not a big deal either way.

**Comment by cbizon** [comment]
I don't see any reason not to make the change you outline.  Feel free from my perspective.

**Comment by larrybabb** [comment]
agreed
